# This rule is not used by the project apis itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the api.kubeall.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: apis
    app.kubernetes.io/managed-by: kustomize
  name: image-editor-role
rules:
- apiGroups:
  - api.kubeall.io
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.kubeall.io
  resources:
  - images/status
  verbs:
  - get
