# This rule is not used by the project apis itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over api.kubeall.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: apis
    app.kubernetes.io/managed-by: kustomize
  name: image-admin-role
rules:
- apiGroups:
  - api.kubeall.io
  resources:
  - images
  verbs:
  - '*'
- apiGroups:
  - api.kubeall.io
  resources:
  - images/status
  verbs:
  - get
