---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.kubeall.io
  resources:
  - globalsettings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.kubeall.io
  resources:
  - globalsettings/finalizers
  verbs:
  - update
- apiGroups:
  - api.kubeall.io
  resources:
  - globalsettings/status
  verbs:
  - get
  - patch
  - update
